# coding: utf-8

"""
    OpenAPI Petstore

    This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import List, Optional


class EnumArrays(BaseModel):
    """
    EnumArrays
    """ # noqa: E501
    just_symbol: Optional[StrictStr] = None
    array_enum: Optional[List[StrictStr]] = None

    @field_validator('just_symbol')
    def just_symbol_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['>=', '$']):
            raise ValueError("must be one of enum values ('>=', '$')")
        return value

    @field_validator('array_enum')
    def array_enum_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['fish', 'crab']):
                raise ValueError("each list item must be one of ('fish', 'crab')")
        return value

    model_config = ConfigDict(
        validate_assignment=True,
        extra='forbid',
    )

    # Deprecated. Use model_inst.model_dump_json(by_alias=True, exclude_unset=True) instead
    # def to_json(self) -> str:

    # Deprecated. Use EnumArrays.model_validate_json(json_str)
    # @classmethod
    # def from_json(cls, json_str: str):

    # Deprecated. Use EnumArrays.model_validate(obj)
    # @classmethod
    # def from_dict(cls, obj: Dict[str, Any]):



