# coding: utf-8

"""
    OpenAPI Petstore

    This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import List, Optional
from typing_extensions import Annotated
from petstore_api.models.read_only_first import ReadOnlyFirst


class ArrayTest(BaseModel):
    """
    ArrayTest
    """ # noqa: E501
    array_of_string: Optional[Annotated[List[StrictStr], Field(min_length=0, max_length=3)]] = None
    array_of_nullable_float: Optional[List[Optional[StrictFloat]]] = None
    array_array_of_integer: Optional[List[List[StrictInt]]] = None
    array_array_of_model: Optional[List[List[ReadOnlyFirst]]] = None

    model_config = ConfigDict(
        validate_assignment=True,
        extra='allow',
    )

    # Deprecated. Use model_inst.model_dump_json(by_alias=True, exclude_unset=True) instead
    # def to_json(self) -> str:

    # Deprecated. Use ArrayTest.model_validate_json(json_str)
    # @classmethod
    # def from_json(cls, json_str: str):

    # Deprecated. Use ArrayTest.model_validate(obj)
    # @classmethod
    # def from_dict(cls, obj: Dict[str, Any]):



