# coding: utf-8

"""
    OpenAPI Petstore

    This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Optional


class Capitalization(BaseModel):
    """
    Capitalization
    """ # noqa: E501
    small_camel: Optional[StrictStr] = Field(default=None, alias="smallCamel")
    capital_camel: Optional[StrictStr] = Field(default=None, alias="CapitalCamel")
    small_snake: Optional[StrictStr] = Field(default=None, alias="small_Snake")
    capital_snake: Optional[StrictStr] = Field(default=None, alias="Capital_Snake")
    sca_eth_flow_points: Optional[StrictStr] = Field(default=None, alias="SCA_ETH_Flow_Points")
    att_name: Optional[StrictStr] = Field(default=None, description="Name of the pet ", alias="ATT_NAME")

    model_config = ConfigDict(
        validate_assignment=True,
        extra='allow',
    )

    # Deprecated. Use model_inst.model_dump_json(by_alias=True, exclude_unset=True) instead
    # def to_json(self) -> str:

    # Deprecated. Use Capitalization.model_validate_json(json_str)
    # @classmethod
    # def from_json(cls, json_str: str):

    # Deprecated. Use Capitalization.model_validate(obj)
    # @classmethod
    # def from_dict(cls, obj: Dict[str, Any]):



