# coding: utf-8

"""
    OpenAPI Petstore

    This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, Dict, List, Optional


class NullableClass(BaseModel):
    """
    NullableClass
    """ # noqa: E501
    required_integer_prop: Optional[StrictInt]
    integer_prop: Optional[StrictInt] = None
    number_prop: Optional[StrictFloat] = None
    boolean_prop: Optional[StrictBool] = None
    string_prop: Optional[StrictStr] = None
    date_prop: Optional[date] = None
    datetime_prop: Optional[datetime] = None
    array_nullable_prop: Optional[List[Dict[str, Any]]] = None
    array_and_items_nullable_prop: Optional[List[Optional[Dict[str, Any]]]] = None
    array_items_nullable: Optional[List[Optional[Dict[str, Any]]]] = None
    object_nullable_prop: Optional[Dict[str, Dict[str, Any]]] = None
    object_and_items_nullable_prop: Optional[Dict[str, Optional[Dict[str, Any]]]] = None
    object_items_nullable: Optional[Dict[str, Optional[Dict[str, Any]]]] = None

    model_config = ConfigDict(
        validate_assignment=True,
        extra='allow',
    )

    # Deprecated. Use model_inst.model_dump_json(by_alias=True, exclude_unset=True) instead
    # def to_json(self) -> str:

    # Deprecated. Use NullableClass.model_validate_json(json_str)
    # @classmethod
    # def from_json(cls, json_str: str):

    # Deprecated. Use NullableClass.model_validate(obj)
    # @classmethod
    # def from_dict(cls, obj: Dict[str, Any]):



