# coding: utf-8

"""
    OpenAPI Petstore

    This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import List, Optional


class CircularAllOfRef(BaseModel):
    """
    CircularAllOfRef
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, alias="_name")
    second_circular_all_of_ref: Optional[List[SecondCircularAllOfRef]] = Field(default=None, alias="secondCircularAllOfRef")

    model_config = ConfigDict(
        validate_assignment=True,
        extra='forbid',
    )

    # Deprecated. Use model_inst.model_dump_json(by_alias=True, exclude_unset=True) instead
    # def to_json(self) -> str:

    # Deprecated. Use CircularAllOfRef.model_validate_json(json_str)
    # @classmethod
    # def from_json(cls, json_str: str):

    # Deprecated. Use CircularAllOfRef.model_validate(obj)
    # @classmethod
    # def from_dict(cls, obj: Dict[str, Any]):


from petstore_api.models.second_circular_all_of_ref import SecondCircularAllOfRef
# TODO: Rewrite to not use raise_errors
CircularAllOfRef.model_rebuild(raise_errors=False)

