# coding: utf-8

"""
    OpenAPI Petstore

    This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from importlib import import_module
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Union
from petstore_api.models.creature_info import CreatureInfo


from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from petstore_api.models.hunting_dog import HuntingDog

class Creature(BaseModel):
    """
    Creature
    """ # noqa: E501
    info: CreatureInfo
    type: StrictStr

    model_config = ConfigDict(
        validate_assignment=True,
        extra='forbid',
    )
    # JSON field name that stores the object type
    __discriminator_property_name: ClassVar[str] = 'type'

    # discriminator mappings
    __discriminator_value_class_map: ClassVar[Dict[str, str]] = {
        'Hunting__Dog': 'HuntingDog'
    }

    @classmethod
    def get_discriminator_value(cls, obj: Dict[str, Any]) -> Optional[str]:
        """Returns the discriminator value (object type) of the data"""
        discriminator_value = obj[cls.__discriminator_property_name]
        if discriminator_value:
            return cls.__discriminator_value_class_map.get(discriminator_value)
        else:
            return None


    # Deprecated. Use model_inst.model_dump_json(by_alias=True, exclude_unset=True) instead
    # def to_json(self) -> str:

    # Deprecated. Use Creature.model_validate_json(json_str)
    # @classmethod
    # def from_json(cls, json_str: str):

    # Deprecated. Use Creature.model_validate(obj)
    # @classmethod
    # def from_dict(cls, obj: Dict[str, Any]):



