# coding: utf-8

"""
    Echo Server API

    Echo Server API

    The version of the OpenAPI document: 0.1.0
    Contact: team@openapitools.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import List, Optional


class Query(BaseModel):
    """
    Query
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="Query")
    outcomes: Optional[List[StrictStr]] = None

    @field_validator('outcomes')
    def outcomes_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['SUCCESS', 'FAILURE', 'SKIPPED']):
                raise ValueError("each list item must be one of ('SUCCESS', 'FAILURE', 'SKIPPED')")
        return value

    model_config = ConfigDict(
        validate_assignment=True,
        extra='forbid',
    )

    # Deprecated. Use model_inst.model_dump_json(by_alias=True, exclude_unset=True) instead
    # def to_json(self) -> str:

    # Deprecated. Use Query.model_validate_json(json_str)
    # @classmethod
    # def from_json(cls, json_str: str):

    # Deprecated. Use Query.model_validate(obj)
    # @classmethod
    # def from_dict(cls, obj: Dict[str, Any]):



