# coding: utf-8

"""
    Echo Server API

    Echo Server API

    The version of the OpenAPI document: 0.1.0
    Contact: team@openapitools.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from pydantic import BaseModel, ConfigDict, StrictStr
from typing import List, Optional


class TestQueryStyleFormExplodeTrueArrayStringQueryObjectParameter(BaseModel):
    """
    TestQueryStyleFormExplodeTrueArrayStringQueryObjectParameter
    """ # noqa: E501
    values: Optional[List[StrictStr]] = None

    model_config = ConfigDict(
        validate_assignment=True,
        extra='forbid',
    )

    # Deprecated. Use model_inst.model_dump_json(by_alias=True, exclude_unset=True) instead
    # def to_json(self) -> str:

    # Deprecated. Use TestQueryStyleFormExplodeTrueArrayStringQueryObjectParameter.model_validate_json(json_str)
    # @classmethod
    # def from_json(cls, json_str: str):

    # Deprecated. Use TestQueryStyleFormExplodeTrueArrayStringQueryObjectParameter.model_validate(obj)
    # @classmethod
    # def from_dict(cls, obj: Dict[str, Any]):



