# coding: utf-8

"""
    Echo Server API

    Echo Server API

    The version of the OpenAPI document: 0.1.0
    Contact: team@openapitools.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from datetime import datetime
from pydantic import ConfigDict, Field, StrictStr
from typing import Optional
from openapi_client.models.query import Query


class DataQuery(Query):
    """
    DataQuery
    """ # noqa: E501
    suffix: Optional[StrictStr] = Field(default=None, description="test suffix")
    text: Optional[StrictStr] = Field(default=None, description="Some text containing white spaces")
    var_date: Optional[datetime] = Field(default=None, description="A date", alias="date")

    model_config = ConfigDict(
        validate_assignment=True,
        extra='forbid',
    )

    # Deprecated. Use model_inst.model_dump_json(by_alias=True, exclude_unset=True) instead
    # def to_json(self) -> str:

    # Deprecated. Use DataQuery.model_validate_json(json_str)
    # @classmethod
    # def from_json(cls, json_str: str):

    # Deprecated. Use DataQuery.model_validate(obj)
    # @classmethod
    # def from_dict(cls, obj: Dict[str, Any]):



