# coding: utf-8

"""
    Echo Server API

    Echo Server API

    The version of the OpenAPI document: 0.1.0
    Contact: team@openapitools.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr, field_validator
from typing import List, Optional
from openapi_client.models.string_enum_ref import StringEnumRef


class DefaultValue(BaseModel):
    """
    to test the default value of properties
    """ # noqa: E501
    array_string_enum_ref_default: Optional[List[StringEnumRef]] = None
    array_string_enum_default: Optional[List[StrictStr]] = None
    array_string_default: Optional[List[StrictStr]] = None
    array_integer_default: Optional[List[StrictInt]] = None
    array_string: Optional[List[StrictStr]] = None
    array_string_nullable: Optional[List[StrictStr]] = None
    array_string_extension_nullable: Optional[List[StrictStr]] = None
    string_nullable: Optional[StrictStr] = None

    @field_validator('array_string_enum_default')
    def array_string_enum_default_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['success', 'failure', 'unclassified']):
                raise ValueError("each list item must be one of ('success', 'failure', 'unclassified')")
        return value

    model_config = ConfigDict(
        validate_assignment=True,
        extra='forbid',
    )

    # Deprecated. Use model_inst.model_dump_json(by_alias=True, exclude_unset=True) instead
    # def to_json(self) -> str:

    # Deprecated. Use DefaultValue.model_validate_json(json_str)
    # @classmethod
    # def from_json(cls, json_str: str):

    # Deprecated. Use DefaultValue.model_validate(obj)
    # @classmethod
    # def from_dict(cls, obj: Dict[str, Any]):



