# coding: utf-8

"""
    Echo Server API

    Echo Server API

    The version of the OpenAPI document: 0.1.0
    Contact: team@openapitools.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Optional, Union
from typing_extensions import Annotated


class NumberPropertiesOnly(BaseModel):
    """
    NumberPropertiesOnly
    """ # noqa: E501
    number: Optional[Union[StrictFloat, StrictInt]] = None
    var_float: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="float")
    double: Optional[Union[Annotated[float, Field(le=50.2, strict=True, ge=0.8)], Annotated[int, Field(le=50, strict=True, ge=1)]]] = None

    model_config = ConfigDict(
        validate_assignment=True,
        extra='forbid',
    )

    # Deprecated. Use model_inst.model_dump_json(by_alias=True, exclude_unset=True) instead
    # def to_json(self) -> str:

    # Deprecated. Use NumberPropertiesOnly.model_validate_json(json_str)
    # @classmethod
    # def from_json(cls, json_str: str):

    # Deprecated. Use NumberPropertiesOnly.model_validate(obj)
    # @classmethod
    # def from_dict(cls, obj: Dict[str, Any]):



