# coding: utf-8

"""
    OpenAPI Petstore

    This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Optional


class DummyModel(BaseModel):
    """
    DummyModel
    """ # noqa: E501
    category: Optional[StrictStr] = None
    self_ref: Optional[SelfReferenceModel] = None

    model_config = ConfigDict(
        validate_assignment=True,
        extra='allow',
    )

    # Deprecated. Use model_inst.model_dump_json(by_alias=True, exclude_unset=True) instead
    # def to_json(self) -> str:

    # Deprecated. Use DummyModel.model_validate_json(json_str)
    # @classmethod
    # def from_json(cls, json_str: str):

    # Deprecated. Use DummyModel.model_validate(obj)
    # @classmethod
    # def from_dict(cls, obj: Dict[str, Any]):


from petstore_api.models.self_reference_model import SelfReferenceModel
# TODO: Rewrite to not use raise_errors
DummyModel.model_rebuild(raise_errors=False)

